/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddPoints: typeof import('./src/components/Bass/Toolbar/AddPoints.vue')['default']
    BassFooter: typeof import('./src/components/Bass/BassFooter.vue')['default']
    BassHeader: typeof import('./src/components/Bass/BassHeader.vue')['default']
    BassToolbar: typeof import('./src/components/Bass/BassToolbar.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    GameMap: typeof import('./src/components/GameMap.vue')['default']
    Markdown: typeof import('./src/components/Model/Markdown.vue')['default']
    Points: typeof import('./src/components/Bass/Toolbar/Points.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwitchMap: typeof import('./src/components/Bass/Toolbar/SwitchMap.vue')['default']
    Tooltip: typeof import('./src/components/Map/Tooltip.vue')['default']
  }
}
