/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddMarker: typeof import('./src/client/components/Map/AddMarker.vue')['default']
    BaseLeftMenu: typeof import('./src/client/components/Base/BaseLeftMenu.vue')['default']
    ContextMenu: typeof import('./src/client/components/Map/ContextMenu.vue')['default']
    Cropped: typeof import('./src/client/components/Model/Cropped.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconDelete: typeof import('@element-plus/icons-vue')['Delete']
    ElIconEdit: typeof import('@element-plus/icons-vue')['Edit']
    ElIconLink: typeof import('@element-plus/icons-vue')['Link']
    ElIconPlus: typeof import('@element-plus/icons-vue')['Plus']
    ElIconUpload: typeof import('@element-plus/icons-vue')['Upload']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    GameMap: typeof import('./src/client/components/Map/GameMap.vue')['default']
    HelloWorld: typeof import('./src/client/components/HelloWorld.vue')['default']
    Markdown: typeof import('./src/client/components/Model/Markdown.vue')['default']
    MarkerLayer: typeof import('./src/client/components/Map/MarkerLayer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
