/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BassDrawer: typeof import('./src/components/Bass/BassDrawer.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconSearch: typeof import('@element-plus/icons-vue')['Search']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    MapIndex: typeof import('./src/components/Map/MapIndex.vue')['default']
    MapLoading: typeof import('./src/components/Model/MapLoading.vue')['default']
    Markdown: typeof import('./src/components/Markdown/Markdown.vue')['default']
    MarkerLayer: typeof import('./src/components/Map/MarkerLayer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
